[package]
name = "evenpw"
description="a cli application to generate easy to type passwords"
version = "0.1.0"
edition = "2021"
license="MIT"

[dependencies]
clap = "4.5.4"
copypasta = "0.10.1"
rand = "0.8.5"
